export const SELECT_TRIP = 'SELECT_TRIP';

export const FETCH_LIST = 'FETCH_LIST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_ERROR = 'FETCH_LIST_ERROR';

export const FETCH_POINTS = 'FETCH_POINTS';
export const FETCH_POINTS_SUCCESS = 'FETCH_POINTS_SUCCESS';
export const FETCH_POINTS_ERROR = 'FETCH_POINTS_ERROR';

export const DRAW_TRIP_LINE = 'DRAW_TRIP_LINE';
export const DRAW_TRIP_LINE_SUCCESS = 'DRAW_TRIP_LINE_SUCCESS';
export const DRAW_TRIP_LINE_ERROR = 'DRAW_TRIP_LINE_ERROR';